# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Dhiraj Shah
tagline:          'A personal blog'
description:      'Coming soon'
url:              http://dhirajshah.com
paginate:         1
baseurl:          "/"

author:
  name:           'Dhiraj Shah'
  url:            https://twitter.com/dhiraj_sh

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dhirajshah/dhirajshah.github.io

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist