# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Dhiraj Shah
tagline:          'A personal blog'
description:      'Coming soon'
url:              http://dhirajshah.github.io
baseurl:          /

author:
  name:           'Dhiraj Shah'
  url:            https://twitter.com/dhiraj_sh

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist